// var x = ColonyWrapping(colonySize: 7)
// x.setCellAlive(xCoor: 3, yCoor: 6)
// x.setCellAlive(xCoor: 1, yCoor: 6)
// x.setCellAlive(xCoor: 4, yCoor: 3)
// x.setCellAlive(xCoor: 3, yCoor: 5)
// x.setCellAlive(xCoor: 2, yCoor: 4)
// x.setCellAlive(xCoor: 1, yCoor: 3)
// x.setCellAlive(xCoor: 3, yCoor: 4)
// x.setCellAlive(xCoor: 5, yCoor: 6)
// x.setCellAlive(xCoor: 0, yCoor: 0)
// x.setCellAlive(xCoor: 1, yCoor: 0)
// print(x)
// x.wrappingEvolve()
// print(x)
// x.wrappingEvolve()
// print(x)
// x.wrappingEvolve()
colonyVC()
